- name: Install
  ansible.builtin.yum:
      name: nginx
      state: latest

- name: restart nginx
  ansible.builtin.systemd:
      state: restarted
      name: nginx
      enabled: yes

- name: Include download task
  include_role:
    name:  common
    tasks_from:  download

- name:  Remove Old Content
# ansible.builtin.systemd:
#      state: restarted
  ansible.builtin.file:
      path:  \usr\share\nginx\html
      state: absent