- name: Add roboshop app user
  ansible.builtin.user:
    name: roboshop
  when: APP_TYPE == "backend"
  register: app_user_info

- name: Include Dowload from GitHub
  include_tasks: download-from-github.yml
  when: APP_VERSION is not defined

- name: Include Dowload from Nexus
  include_tasks: download-from-nexus.yml
  when: APP_VERSION is defined
