- name: Play level variables
  hosts: all

  tasks:
    - name: Access to URL in task 1
      ansible.builtin.debug:
        msg: URL in task 1 = {{URL}}

    - name: Access to URL in task 2
      ansible.builtin.debug:
        msg: URL in task 2 = {{URL}}
