help:
		@grep  '#### '  Makefile  | grep  -v  grep | sed -e "s####//"

cart: #### Setup Cart Component
	@bash Components/cat.sh

catalogue: #### Setup Catalogue component
	@bash Components/catalogue.sh

user: #### Setup User component
	@bash Components/user.sh

shipping: #### Setup Shipping Component
	@bash Components/shipping.sh

payment: #### Setup Payment Component
	@bash Components/payment.sh

frontend: #### Setup frontend Component
	@bash	Components/frontend.sh

mysql: #### Setup mysql Component
	@bash Components/mysql.sh

redis: #### Setup redis Component
	@bash	Components/redis.sh

rabbitmq: #### Setup rabbitmq
	@bash	Compnents/rabbitmq.sh

mongodb:
